### ISSUE TITLE
Update operator to latest version to support pgvector

### ISSUE THREAD

**Issue by Phiph** [syntasso/promise-postgresql#4]
Hey, 

I'd like to use Postgres pgvector plugin. 

From what I can tell that has recently been added to the operator and underlying cluster in a release around march time. 

https://github.com/zalando/postgres-operator/pull/2580

May the operator/promise here be updated?

Thanks,

Phill

**Comment by abangser** [comment]
Absolutely Phill! I have just made the update and would love to know if it works as you would expect before closing this issue.

Also for future needs just know you are welcome to make a PR on this which might unblock you faster as then you could always work off that branch til it is merged. I made some updates today to make it pin to a specific version which may make that easier to spot as well in the future 🤞

**Comment by Phiph** [comment]
Legendary thank you! It's useful for me to see the pattern that you use to update promises :) I'll contribute next time - promise ;) 

I'll check it out today and let you know what happens :D Thank you so much!

**Comment by abangser** [comment]
Going to close this for now @Phiph, but please do reopen or reach out if you have any issues! 🎉
